name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt-get install bash cmake qt5-default qttools5-dev libqt5help5 libqt5svg5 libqt5svg5-dev libqt5test5 lcov
      - name: Build tests
        run: cd tests && make tests
      - name: Run tests
        run: |
          QT_QPA_PLATFORM=offscreen tests/_build/unittests
          lcov -c -d tests/_build/ -o coverage.info --exclude '/usr/*' --exclude '*dxflib*' --exclude '*_build/unittests_autogen*'
          lcov --list coverage.info
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

  test-urls:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Find broken URLs
        run: tests/scripts/find_broken_urls.sh
